use MER5;
SELECT CLIENT.nom, VEHICLE.marca, TIPUS_VEHICLE.nom, CITA.data, CITA.ubicacio, CLIENT_VEHICLE.data_fi
FROM CLIENT, VEHICLE, TIPUS_VEHICLE, CITA, CLIENT_VEHICLE
WHERE CLIENT.DNI = CLIENT_VEHICLE.CLIENT_DNI AND
	VEHICLE.num_carroseria = CLIENT_VEHICLE.num_carroseria AND
	TIPUS_VEHICLE.ID = VEHICLE.TIPUS_VEHICLE_ID AND
    CLIENT_VEHICLE.ID = CITA.VEHICLE_ID;