use MER7;
select TICKET.num_factura, TICKET.data, EMPLEAT.nom, EMPLEAT.cognom
FROM TICKET, EMPLEAT, PRODUCTE, LINEA_TICKET
WHERE PRODUCTE.ID = LINEA_TICKET.PRODUCTE_ID AND
TICKET.NUM = LINEA_TICKET.TICKET_NUM AND
EMPLEAT.ID = TICKET.EMPLEAT_ID AND
PRODUCTE.nom = "Rellotge"