use MER4;
SELECT CLIENT.nom, CLIENT.cognom, VENEDOR.nom, VENEDOR.cognom, POLISSA.num_polissa, TIPUS_POLISSA.nom
FROM CLIENT, VENEDOR, POLISSA, TIPUS_POLISSA
WHERE CLIENT.DNI = POLISSA.CLIENT_DNI and VENEDOR.DNI=POLISSA.VENEDOR_DNI and
		TIPUS_POLISSA.ID = POLISSA.TIPUS_DE_POLISSA_ID;